# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{haxor_gem}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Conroy-Finn"]
  s.date = %q{2010-12-03}
  s.description = %q{Haxor through gem}
  s.email = %q{james@logi.cl}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "CHANGELOG.markdown",
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "lib/rubygems/commands/haxor_command.rb",
    "lib/rubygems_plugin.rb"
  ]
  s.homepage = %q{http://github.com/jcf/haxor_gem}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{haxor_gem}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Haxor through gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

